apiVersion: v1
kind: Pod
metadata:
  name: touch1 
  labels:
    app: nextflow
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: debian
    command: ["bash", "-c", "echo Hello world! > /data/hello.txt"]
    volumeMounts:
    - name: site-data
      mountPath: /data
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: gluster-claim 
