apiVersion: v1
kind: Pod
metadata:
  name: ls-1 
  labels:
    app: nextflow
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: debian
    command: ["bash", "-c", "ls -la  /data/"]
    volumeMounts:
    - name: site-data
      mountPath: /data
  volumes:
  - name: site-data
    persistentVolumeClaim:
      claimName: gluster-claim 
