apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv   
spec:
  capacity:
    storage: 1Gi     
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: glusterfs-heketi
    path: /data 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain 

